// This file is generated by Slice Machine. Update with care!

import GoogleMaps from './GoogleMaps';
import LocationDescription from './LocationDescription';
import LocationHero from './LocationHero';
import TestSlice from './TestSlice';

export {
	GoogleMaps,
	LocationDescription,
	LocationHero,
	TestSlice,
};

export const components = {
	google_maps: GoogleMaps,
	location_description: LocationDescription,
	location_hero: LocationHero,
	test_slice: TestSlice,
};
