// This file is generated by Slice Machine. Update with care!

import GoogleMaps from './GoogleMaps';
import LocationDescription from './LocationDescription';
import LocationHero from './LocationHero';
import LocationInformations from './LocationInformations';
import OperationHours from './OperationHours';
import TestSlice from './TestSlice';

export {
	GoogleMaps,
	LocationDescription,
	LocationHero,
	LocationInformations,
	OperationHours,
	TestSlice,
};

export const components = {
	google_maps: GoogleMaps,
	location_description: LocationDescription,
	location_hero: LocationHero,
	location_informations: LocationInformations,
	operation_hours: OperationHours,
	test_slice: TestSlice,
};
