// This file is generated by Slice Machine. Update with care!

import ImagePush from './ImagePush';
import LocationDescription from './LocationDescription';
import LocationHero from './LocationHero';

export {
	ImagePush,
	LocationDescription,
	LocationHero,
};

export const components = {
	image_push: ImagePush,
	location_description: LocationDescription,
	location_hero: LocationHero,
};
